- name: Install Apache on  amazon Web server
  hosts: web2
  tasks:
    - name: Installing httpd software
      package:
        name: "{{httpd}}"
        state: present
    
    - name: Starting httpd services
      service: 
        name: "{{httpd}}"
        state: started
        enabled: yes
